name: lbp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.28+29

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  onesignal_flutter: ^2.6.3
  url_launcher: ^6.0.2
  uuid: 2.2.2
  device_info: ^0.4.0+4
  shared_preferences: ^0.5.2
  gsheets: ^0.2.6
  preferences: ^5.2.0 # preference screen
  provider: ^3.1.0
  footer: ^0.0.3
  intl: ^0.16.1
  date_format: ^1.0.6
  progress_indicator_button: ^0.0.3
  firebase_crashlytics: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.17.0
  build_runner: ^1.10.3

flutter:
  uses-material-design: true
  assets:
     - images/

  fonts:
   - family: Raleway
     fonts:
       - asset: fonts/Raleway-Regular.ttf
       - asset: fonts/Raleway-Thin.ttf
         style: normal

